version: "3"
services:
  dpc-website:
    build: .
    environment:
      - TOPBAR_DANSPLUGINS_GITHUB_ORGANIZATION_URL=${TOPBAR_DANSPLUGINS_GITHUB_ORGANIZATION_URL}
      - TOPBAR_DISCORD_SERVER_URL=${TOPBAR_DISCORD_SERVER_URL}
      - TOPBAR_PLAYTEST_SERVER_PMC_URL=${TOPBAR_PLAYTEST_SERVER_PMC_URL}
      - TOPBAR_PATREON_PAGE_URL=${TOPBAR_PATREON_PAGE_URL}
      - TOPBAR_LINKEDIN_PAGE_URL=${TOPBAR_LINKEDIN_PAGE_URL}
      - TOPBAR_RPKIT_GITHUB_ORGANIZATION_URL=${TOPBAR_RPKIT_GITHUB_ORGANIZATION_URL}
    ports:
      - "3000:3000"
    volumes:
      - ./node_modules:/app/node_modules